### ISSUE TITLE
A strange(?) copy of MeetNinja

### ISSUE THREAD

**Issue by SHUR1K-N** [yash3001/Meet-God#2]
This is a poorly plagiarized copy of my [MeetNinja](https://GitHub.com/SHUR1K-N/MeetNinja-Google-Meet-Bot) tool. I have no issues with the open source aspect of code, but to copy-paste it to _this_ extent (even the banner elements still have ″MeetNinja″ still written in them), along with some elements from even the initial _README_, and then calling it yours and ″perfect″; that's just bad. This is not the correct channel/way of doing such things. You are supposed to ″Fork″ my repository and make changes to _your_ version of it (I _saw_ you forked MeetNinja and then unforked it as well, so it's not like you did not know of it). This is quite indecent and frankly, douchy. Super uncool.

**Comment by yash3001** [comment]
I just took the basic idea of opening meet without getting the "not allowed error" error (i am new to selenium). Rest everything is written by me. I am a linux user and i know the font of your meetninja banner. Its comes from the tool "figlet" and the "bloody" font. I have it in my zshrc. I saw you using that font and thought it was a nice idea. My code has threading/multiprocessing so you can add/modify/delete meetings from the schedule. It also keeps a track of the number of people and leaves only if they are less than 20 and not after a particular time limit. There are several other features that i added, will place them in the readme

Yes I took some of your ideas, but IT IS open source, right? The readme is not complete and In the end i was eventually gonna include your repo link in in the reference section. I still appreciate you code, you did a great job there.

p.s. Also if you remember me from reddit, i was just searching for a way to login into google meet without getting blocked. You had written the perfect code for that so why waste time write the same code myself, so i copied that section only.

**Comment by yash3001** [comment]
As for the forking, i did it by mistake yesterday while looking for some readme ideas. I have been working on this project from the past 4-5 days

**Comment by yash3001** [comment]
Also go through the code once, you will __clearly__ see the difference. Also its super uncool on your part to say its a copy-paste.

**Comment by SHUR1K-N** [comment]
>The readme is not complete and In the end i was eventually gonna include your repo link in in the reference section.

It is always good practice to _initially_ clarify these things in your documentation to not create such impressions. That's what makes it "super uncool" on your part.

> i know the font of your meetninja banner. Its comes from the tool "figlet" and the "bloody" font. I have it in my zshrc. I saw you using that font and thought it was a nice idea.

> Also go through the code once, you will **clearly** see the difference. Also its super uncool on your part to say its a copy-paste.

It is not about the banner or the font, it is understandable that you found it cool, no, but it is about the surrounding elements; much of it is so carelessly copy-pasted that it still has some MeetNinja text still attached to it. An example of this is [line #118](https://github.com/yash3001/Meet-God/blob/06631890fb14683d2773dec350474bfe81eacb12/Bot.py#L118) still literally has the word "MeetNinja" in it (and you say it is uncool on my part to say it's a copy-paste). I am not even referring to the variable names because I can understand if they are reused due to them making sense to you, I am not being petty; just frankly expressing how it was uncool, and maybe take this as a lesson to credit/refer _initially_. Otherwise it's just bad code. Not technical code, ethical/moral code.

**Comment by SHUR1K-N** [comment]
Also, I would advise a separate and unadded/uncommitted/unpushed "personal" version of your program that has your login credentials in it since [these previous commits of yours](https://github.com/yash3001/Meet-God/commit/162469dfe21a3d47aa78e4af84e825737c2bbfe7) always remain in your "Commits" for just about anyone to see.

**Comment by yash3001** [comment]
> and maybe take this as a lesson to credit/refer initially

As i said before also, i was gonna include your repo's link in the readme. this project is not complete as well as the readme. You are just so quick to jump to conclusions.

**Comment by yash3001** [comment]
> Also, I would advise a separate and unadded/uncommitted/unpushed "personal" version of your program that has your login credentials in it since these previous commits of yours always remain in your "Commits" for just about anyone to see.

Hmm that is my bad, after adding some feature or removing some bug, i sometimes straight away commit and push the code realizing later about the credentials

**Comment by SHUR1K-N** [comment]
> You are just so quick to jump to conclusions.

This is the internet. Your intentions are not crystal clear to every other person. _Your_ "was gonna" is not foreseen by another person for them to intrinsically know. For them, it's just bad practice at first glance. Hence, it is common and standard ethical practice to credit/mention/refer in the earliest of stages since all your commits can be traced and seen since the conception of your repository.

**Comment by yash3001** [comment]
i will complete the readme by tomorrow, will include you repo link, also i will call it mine because i have been working on it for about a week now, and will delete this issue tomorrow. I am sorry if this caused some kind of confusion.

**Comment by SHUR1K-N** [comment]
Your version is _definitely_ your own work, no doubt about that. _If_ by the end of your project, there _is_ however some element that is learned or taken from another source (be it a person, their code, or whatever), it is just common/standard practice to mention it/them. By that, I mean if your project deviates from mine completely, you need not mention my repository; just saying.

All the best in your future endeavors.
